# Generated by Django 4.2.5 on 2023-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("band", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="song",
            name="audio_file",
            field=models.FileField(
                default="path/to/default_audio.mp3", upload_to="audio/"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(default="", max_length=100),
        ),
    ]
