# Generated by Django 4.2.5 on 2023-09-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("band", "0002_song_artist_song_audio_file_song_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.CharField(max_length=100),
        ),
    ]
